services:
  shaymin-local:
    image: itzg/minecraft-server:java21-graalvm
    container_name: shaymin-local
    tty: true
    stdin_open: true
    ports:
      - 8119:25565
      - 8119:25565/udp
    environment:
      UID: becke
      GID: becke
      EULA: "TRUE"
      TYPE: NEOFORGE
      # CUSTOM_SERVER: "arclight-neoforge-1.21.1-1.0.2-SNAPSHOT-0769551.jar"
      VERSION: 1.21.1
      NEOFORGE_VERSION: 21.1.228
      INIT_MEMORY: 4G
      MIN_MEMORY: 8G
      MAX_MEMORY: 16G
      USE_MEOWICE_FLAGS: true
      TZ: Australia/Melbourne
      STOP_SERVER_ANNOUNCE_DELAY: 30
      ENABLE_RCON: true
      SERVER_PORT: 25565
      RCON_PASSWORD: ballin4milk
      BROADCAST_RCON_TO_OPS: true
      DIFFICULTY: normal
      MODE: survival
      MOTD: |
        §3Shaymin Cobblemon §d[2.0-alpha.3]§r
        §kpog§6 who cares lmao §7§kpog
      BROADCAST_CONSOLE_TO_OPS: false
      MAX_PLAYERS: 20
      MAX_WORLD_SIZE: 5000
      SPAWN_PROTECTION: 0
      RCON_CMDS_STARTUP: |
        gamerule mobGriefing false
        gamerule doWardenSpawning false
        gamerule announceAdvancements false
        gamerule doInsomnia false
        gamerule projectilesCanBreakBlocks false
        gamerule commandBlockOutput false
    deploy:
      resources:
        limits:
          cpus: 6
    volumes:
      - ./server:/data
    restart: unless-stopped
networks: {}
