[general]
	#Whether blocks with block entities can be placed in framed blocks
	allowBlockEntities = false
	#If true, only the player who placed the Framed One-Way Window can modify the window direction
	oneWayWindowOwnable = true
	#If true, applying a camo will consume the item and removing the camo will drop it again
	consumeCamoItem = true
	#If true, framed blocks are completely fire proof
	fireproofBlocks = false
